all:
#	gcc -std=c11 -march=native  -o crypto_xor_find_more_bytes_key.exe crypto_xor_find_more_bytes_key.c
	gcc -std=c11 -Wall -Wextra -pedantic -Werror -Wshadow -Wstrict-overflow -fno-strict-aliasing -march=native  -o pkcs7.exe pkcs7.c
